Repository microsoft/react-native-macos, pull requests merged in 2022-02, with the labels that each got.

#996 [chore] address codeowners to reflect current status
  .github/CODEOWNERS
Labels: JSHost, ⚙️ Infra

#712 Add Docs for Hermes Handoff Jan 2020
  docs/hermes-jan-2020.md
Labels: AutoMerge

#1001 [chore] address security-related issues & bump shelljs
  package.json
  packages/react-native-macos-init/yarn.lock
  packages/rn-tester/yarn.lock
  repo-config/package.json
  yarn.lock
Labels: ⚙️ Infra

#997 [chore] bump all references to Node 16
  .ado/templates/android-build-office.yml
  .ado/templates/apple-node-setup.yml
  .circleci/config.yml
  Brewfile
  package.json
Labels: ⚙️ Infra

#979 [chore] small tweaks & bump VMs in CI
  .ado/android-pr.yml
  .ado/apple-integration.yml
  .ado/apple-pr.yml
  .ado/publish.yml
  .ado/variables/mac.yml
  .ado/variables/vars.yml
  packages/rn-tester/Podfile.lock
  packages/rn-tester/RNTesterIntegrationTests/RNTesterSnapshotTests.m
  packages/rn-tester/RNTesterIntegrationTests/ReferenceImages/packages-rn-tester-js-RNTesterApp.ios/testLayoutExample_1-iOS15@3x.png
  packages/rn-tester/RNTesterIntegrationTests/ReferenceImages/packages-rn-tester-js-RNTesterApp.ios/testScrollViewExample_1-iOS15@3x.png
  packages/rn-tester/RNTesterIntegrationTests/ReferenceImages/packages-rn-tester-js-RNTesterApp.ios/testSwitchExample_1-iOS15@3x.png
  packages/rn-tester/RNTesterIntegrationTests/ReferenceImages/packages-rn-tester-js-RNTesterApp.ios/testTextExample_1-iOS15@3x.png
  packages/rn-tester/RNTesterIntegrationTests/ReferenceImages/packages-rn-tester-js-RNTesterApp.ios/testViewExample_1-iOS15@3x.png
Labels: JSHost, ⚙️ Infra

#1022 [Main] Adding patches required for running RN66 in Office apps
  .ado/templates/apple-droid-node-patching.yml
  android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec
  android-patches/patches/JniUtils/ReactAndroid/src/main/java/com/facebook/react/fabric/jni/Android.mk
  android-patches/patches/JniUtils/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni/Android.mk
  android-patches/patches/JniUtils/ReactAndroid/src/main/jni/react/jni/Android.mk
  android-patches/patches/JniUtils/ReactCommon/react/renderer/components/progressbar/Android.mk
  android-patches/patches/JniUtils/ReactCommon/react/renderer/components/slider/Android.mk
  android-patches/patches/JniUtils/ReactCommon/react/renderer/components/switch/Android.mk
  android-patches/patches/JniUtils/ReactCommon/react/renderer/textlayoutmanager/Android.mk
  android-patches/patches/OfficeRNHost/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactBridge.java
  android-patches/patches/RootViewAttach/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java
Labels: Android
