Repository microsoft/react-native-macos, pull requests merged in 2022-08, with the labels that each got.

#1308 [RN][macos] Enable Hermes for RNTester
  packages/rn-tester/Podfile
  packages/rn-tester/RNTester-macOS/AppDelegate.mm
Labels: Partner: Facebook

#1318 Revert "Alleviate excessive layout jittering when resizing window (#439)"
  React/Base/RCTRootView.m
  React/Modules/RCTUIManager.m
Labels: Partner: Facebook

#1321 Remove TextInput setting insertionPointColor
  Libraries/Text/TextInput/Multiline/RCTUITextView.m
  Libraries/Text/TextInput/Singleline/RCTUITextField.m
Labels: Partner: Facebook

#1272 Fix RCTImageCache on macOS
  Libraries/Image/RCTImageCache.m
Labels: Partner: Facebook

#1332 Add fragmentLinePadding for multiline shadow view to track TextView correctly
  Libraries/Text/TextInput/RCTBaseTextInputShadowView.m
Labels: Partner: Facebook

#1342 Fix cursor not showing when tabbing into multiline TextInput
  Libraries/Text/TextInput/Multiline/RCTUITextView.m
  React/Views/UIView+React.m
Labels: Partner: Facebook

#1325 Pass callbacks for when grammarCheck, spellCheck and autoCorrect are changed on macOS
  Libraries/Components/TextInput/TextInput.js
  Libraries/Text/TextInput/Multiline/RCTUITextView.m
  Libraries/Text/TextInput/RCTBackedTextInputDelegate.h
  Libraries/Text/TextInput/RCTBaseTextInputView.h
  Libraries/Text/TextInput/RCTBaseTextInputView.m
  Libraries/Text/TextInput/RCTBaseTextInputViewManager.m
  packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js
Labels: Partner: Facebook

#1340 Fix Appearance module to observe application appearance
  React/Base/RCTRootView.m
  React/CoreModules/RCTAppearance.mm
Labels: Partner: Facebook

#1338 Refactor handling of keyDown/keyUp
  React/Views/RCTView.h
  React/Views/RCTView.m
  React/Views/RCTViewKeyboardEvent.h
  React/Views/RCTViewKeyboardEvent.m
  packages/rn-tester/js/examples/KeyboardEventsExample/KeyboardEventsExample.js
Labels: Partner: Facebook

#1279 Cache local images into memory
  React/Base/RCTUtils.m
Labels: Partner: Facebook, Needs: Attention :wave:

#760 Add cursor prop to View and Touchables
  Libraries/Components/View/ReactNativeStyleAttributes.js
  Libraries/Components/View/ReactNativeViewViewConfig.js
  Libraries/Components/View/ReactNativeViewViewConfigMacOS.js
  Libraries/StyleSheet/StyleSheetTypes.js
  Libraries/Text/RCTTextAttributes.m
  React/Base/macOS/RCTUIKit.m
  React/Views/RCTCursor.h
  React/Views/RCTCursor.m
  React/Views/RCTView.h
  React/Views/RCTView.m
  React/Views/RCTViewManager.m
  packages/rn-tester/Podfile.lock
  packages/rn-tester/RNTester/Info.plist
  packages/rn-tester/js/examples/View/ViewExample.js
Labels: Partner: Facebook

#1355 Provide option to not blindly foreground app's lastWindow from deepLinks
  Libraries/LinkingIOS/RCTLinkingManager.h
  Libraries/LinkingIOS/macos/RCTLinkingManager.mm
Labels: Partner: Facebook, Needs: Triage :mag:

#1358 Fix TextInput interfering with Japanese conversion
  Libraries/Text/TextInput/RCTBackedTextInputViewProtocol.h
  Libraries/Text/TextInput/RCTBaseTextInputView.m
  Libraries/Text/TextInput/Singleline/RCTUITextField.m
Labels: Partner: Facebook, Needs: Triage :mag:

#1320 Fix build errors with codegen discovery flag enabled
  packages/rn-tester/Podfile
  scripts/generate-artifacts.js
Labels: Partner: Facebook
